const RANDOM = "RANDOM";
const LOGIN_LOADING = "LOGIN_LOADING";
const LOGIN_ERROR = "LOGIN_ERROR";
const LOGIN_USER = "LOGIN_USER";
const SET_CATEGORIES = "SET_CATEGORIES";
const SET_POSTS = "SET_POSTS";
const LOGOUT_USER = "LOGOUT_USER";
const CHANGE_ACTIVE_LINK = "CHANGE_ACTIVE_LINK";
const SET_DASHBOARD = "SET_DASHBOARD";
const SHOW_ERROR = "SHOW_ERROR";
const SET_LOADING = "SET_LOADING";
const SET_SINGLE_CATEGORY = "SET_SINGLE_CATEGORY";
const SET_SINGLE_POST = "SET_SINGLE_POST";
const SIDEBAR_ACTIVE = "SIDEBAR_ACTIVE";
export {
  RANDOM,
  LOGIN_LOADING,
  LOGIN_ERROR,
  LOGIN_USER,
  SET_CATEGORIES,
  SET_POSTS,
  LOGOUT_USER,
  CHANGE_ACTIVE_LINK,
  SET_DASHBOARD,
  SHOW_ERROR,
  SET_LOADING,
  SET_SINGLE_CATEGORY,
  SET_SINGLE_POST,
  SIDEBAR_ACTIVE,
};
