const SIDEBAR_TOGGLE = "SIDEBAR_TOGGLE";
const CHANGE_ACTIVE_LINK = "CHANGE_ACTIVE_LINK";
const SET_LOADING = "SET_LOADING";
const SET_POSTS = "SET_POSTS";
const SET_CATEGORIES = "SET_CATEGORIES";
const FILTER_POSTS = "FILTER_POSTS";
const FETCH_SINGLE_PRODUCT = "FETCH_SINGLE_PRODUCT";
const SET_TUTORIAL = "SET_TUTORIAL";
const SET_SINGLE_POST = "SET_SINGLE_POST";
export {
  SIDEBAR_TOGGLE,
  CHANGE_ACTIVE_LINK,
  SET_LOADING,
  SET_POSTS,
  SET_CATEGORIES,
  FILTER_POSTS,
  FETCH_SINGLE_PRODUCT,
  SET_TUTORIAL,
  SET_SINGLE_POST,
};
